### ISSUE TITLE
No scroll if in modal box

### ISSUE THREAD

**Issue by funkycram** [humhub/mail#171]
Humhub version 1.4.3

If you write a new message or edit a message, it opens the rich text editor in a modal window.

If your text has many lines, the rich text window has no scroll to go to the begining or the end of the message :
![image](https://user-images.githubusercontent.com/23310825/76196595-cf840a00-61ea-11ea-8865-0e9a9ce27689.png)

Change overflow by auto instead of hidden and the problem is solved :
![image](https://user-images.githubusercontent.com/23310825/76196800-2c7fc000-61eb-11ea-8acc-fdbadf8f4524.png)

Adding this CSS solves the problem :
```
.ProsemirrorEditor.plainMenu .ProseMirror.humhub-ui-richtext {
	overflow: auto !important;
}
```

**Comment by luke-** [comment]
@funkycram Should be fixed. If not please reopen

**Comment by funkycram** [comment]
On Mail v2.0.7 with Humhub v1.10 and Humhub native theme, the problem is still there for new messages.
On the other hand, in conversations, the scrollbar is present.

I could notice that overflow is set to auto (which is right):
![image](https://user-images.githubusercontent.com/23310825/144837895-45d54908-50c1-4c99-bd34-d1e4862b33b7.png)

But, as soon the message gets higher than the textarea, the overflow is changed to none:
![image](https://user-images.githubusercontent.com/23310825/144837830-24f91fb8-ff12-44c5-8d0e-cff20c677eaa.png)

**Comment by funkycram** [comment]
The problem is solved in Humhub 1.13 (and perhaps before).
